name: CI/CD Deployment to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_CREDENTIALS }}
  GKE_CLUSTER: "autopilot-cluster-1"
  GKE_REGION: "us-central1"
  DEPLOYMENT_NAME: "mlops-app"
  REPOSITORY: "us-central1-docker.pkg.dev/cloud-project-474414/dockermlop"
  IMAGE: " asia-south1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/my-docker-repo/my-app"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICEACCOUNT_KEY }}

      - name: Configure GCloud
        run: |
          gcloud config set project $PROJECT_ID
          gcloud auth configure-docker us-central1-docker.pkg.dev
          
      - name: Building and Pushing Image
        run: |
          docker build -t $IMAGE:$GITHUB_SHA .
          docker push $IMAGE:$GITHUB_SHA

      - name: GKE Configuration
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION --project $PROJECT_ID

      - name: Install gke-gcloud-auth-plugin
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
          sudo apt-get update
          sudo apt-get install google-cloud-cli-gke-gcloud-auth-plugin

      - name: Deploying to Kubernetes
        run: |
          kubectl apply -f kubernetes-deployment.yaml
          kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$IMAGE:$GITHUB_SHA

